name: Trigger pipeline of amfoss gitlab project to clone this repo

on:
  push:
    branches:
      - main
    paths:
      - 'member.json'
      - 'alumni.json'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl -X POST \
          -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} \
          -F ref=main \
          https://gitlab.com/amfoss/amfoss/website-v2/trigger/pipeline
        env:
          GITLAB_PIPELINE_TRIGGER_TOKEN: ${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }}