name: Trigger pipeline of amfoss gitlab project to clone this repo

on:
  push:
    branches:
      - main
    paths:
      - 'member.json'
      - 'alumni.json'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline and Show Response
        run: |
          echo "Triggering GitLab pipeline..."
          RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}\n" -X POST \
            -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} \
            -F ref=main \
            -F "variables[TRIGGERED_BY]=github" \
            https://gitlab.com/amfoss/amfoss/website-v2/trigger/pipeline)

          echo "GitLab Response:"
          echo "$RESPONSE"
